wandb_version: 1

data_dir_name:
  desc: null
  value: data
results_dir_name:
  desc: null
  value: results
models_dir_name:
  desc: null
  value: models
input_data_name:
  desc: null
  value: polybert_ffn_morgan_80_20_new.pickle
output_name:
  desc: null
  value: polybert_ffn_morgan_80_20_new_sweep_DUMMY
fold:
  desc: null
  value: 2
rounds:
  desc: null
  value: 1
seed:
  desc: null
  value: 42
sweep_id:
  desc: null
  value: ''
sweep_config:
  desc: null
  value:
    method: grid
    metric:
      name: mae_mean
      goal: minimize
    parameters:
      use_wandb:
        value: true
      arrhenius:
        value: false
      regularisation:
        value: 0
      salt_col:
        value: salt smiles
      salt_encoding:
        value: morgan
      salt_model_name:
        value: ''
      conts:
        value:
        - mw
        - molality
        - temperature_K
      temperature_name:
        value: temperature_K
      device:
        value: cuda
      poly_model_name:
        value: kuelumbus/polyBERT
      poly_encoding:
        value: polybert_tokenizer
      poly_col:
        value: psmiles
      num_polymer_features:
        value: 600
      num_salt_features:
        value: 128
      num_continuous_vars:
        value: 3
      data_fraction:
        value: 0.01
      batch_size:
        value: 16
      accumulation_steps:
        values:
        - 4
        - 8
        - 16
      hidden_size:
        values:
        - 512
        - 1024
        - 2048
      num_hidden_layers:
        values:
        - 1
        - 2
      dropout:
        value: 0.1
      activation_fn:
        value: relu
      init_method:
        value: glorot
      freeze_layers:
        value: 12
      encoder_init_lr:
        value: 1.0e-06
      salt_freeze_layers:
        value: 12
      salt_encoder_init_lr:
        value: 1.0e-06
      output_size:
        value: 1
      lr:
        values:
        - 0.0001
        - 5.0e-05
        - 1.0e-05
      optimizer:
        value: AdamW
      scheduler:
        value: ReduceLROnPlateau
      warmup_steps:
        value: 10
      epochs:
        value: 2
verbose:
  desc: null
  value: false
_wandb:
  desc: null
  value:
    python_version: 3.12.2
    cli_version: 0.17.5
    framework: xgboost
    huggingface_version: 4.43.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1725378365
    t:
      1:
      - 1
      - 5
      - 6
      - 11
      - 49
      - 53
      - 55
      2:
      - 1
      - 5
      - 6
      - 11
      - 49
      - 53
      - 55
      3:
      - 2
      - 16
      - 23
      - 37
      4: 3.12.2
      5: 0.17.5
      6: 4.43.3
      8:
      - 3
      - 5
      13: windows-amd64
accumulation_steps:
  desc: null
  value: 4
activation_fn:
  desc: null
  value: relu
arrhenius:
  desc: null
  value: false
batch_size:
  desc: null
  value: 16
conts:
  desc: null
  value:
  - mw
  - molality
  - temperature_K
data_fraction:
  desc: null
  value: 0.01
device:
  desc: null
  value: cuda
dropout:
  desc: null
  value: 0.1
encoder_init_lr:
  desc: null
  value: 1.0e-06
epochs:
  desc: null
  value: 2
freeze_layers:
  desc: null
  value: 12
hidden_size:
  desc: null
  value: 512
init_method:
  desc: null
  value: glorot
lr:
  desc: null
  value: 0.0001
num_continuous_vars:
  desc: null
  value: 3
num_hidden_layers:
  desc: null
  value: 1
num_polymer_features:
  desc: null
  value: 600
num_salt_features:
  desc: null
  value: 128
optimizer:
  desc: null
  value: AdamW
output_size:
  desc: null
  value: 1
poly_col:
  desc: null
  value: psmiles
poly_encoding:
  desc: null
  value: polybert_tokenizer
poly_model_name:
  desc: null
  value: kuelumbus/polyBERT
regularisation:
  desc: null
  value: 0
salt_col:
  desc: null
  value: salt smiles
salt_encoder_init_lr:
  desc: null
  value: 1.0e-06
salt_encoding:
  desc: null
  value: morgan
salt_freeze_layers:
  desc: null
  value: 12
salt_model_name:
  desc: null
  value: ''
scheduler:
  desc: null
  value: ReduceLROnPlateau
temperature_name:
  desc: null
  value: temperature_K
use_wandb:
  desc: null
  value: true
warmup_steps:
  desc: null
  value: 10
