wandb_version: 1

accumulation_steps:
  value: 4
activation_fn:
  value: relu
arrhenius:
  value: false
batch_size:
  value: 16
conts:
  value:
  - mw
  - molality
  - temperature_K
data_fraction:
  value: 0.01
device:
  value: cuda
dropout:
  value: 0.1
encoder_init_lr:
  value: 1.0e-06
epochs:
  value: 2
freeze_layers:
  value: 12
hidden_size:
  value: 512
init_method:
  value: glorot
lr:
  value: 0.0001
num_continuous_vars:
  value: 3
num_hidden_layers:
  value: 1
num_polymer_features:
  value: 600
num_salt_features:
  value: 128
optimizer:
  value: AdamW
output_size:
  value: 1
poly_col:
  value: psmiles
poly_encoding:
  value: polybert_tokenizer
poly_model_name:
  value: kuelumbus/polyBERT
regularisation:
  value: 0
salt_col:
  value: salt smiles
salt_encoder_init_lr:
  value: 1.0e-06
salt_encoding:
  value: morgan
salt_freeze_layers:
  value: 12
salt_model_name:
  value: ''
scheduler:
  value: ReduceLROnPlateau
temperature_name:
  value: temperature_K
use_wandb:
  value: true
warmup_steps:
  value: 10
